### ISSUE TITLE
Restore Activity.Current without creating a child

### ISSUE THREAD

**Issue by lmolkova** [aspnet/Microsoft.AspNet.TelemetryCorrelation#25]
Once next version of DiagnosticSource (4.6?) is released, it will be possible to assign Activity.Current when it  was lost.

**Comment by stebet** [comment]
Yay! I can get rid of my reflection workaround hack then :) Thank you.

**Comment by lmolkova** [comment]
@stebet if you can use DiagnosticSource package from myget feed, you can get rid of it right now!
