### ISSUE TITLE
Support W3C format for distributed trace context propagation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [aspnet/Microsoft.AspNet.TelemetryCorrelation#26]
Same as https://github.com/aspnet/Hosting/issues/1457 for ASP.NET Core

## Motivation

Support extraction and injection of distributed tracing context in a format of [W3C headers](https://github.com/w3c/distributed-tracing).

Support for new headers in ASP.NET depend on [support](https://github.com/dotnet/corefx/issues/30331) for `tracestate` collection in `Activity` class of `DiagnosticsSource`.

CC: @seth-capistron, @vancem, @jacpull, @lmolkova, @glennc, @davidfowl

**Comment by davidfowl** [comment]
We need to Sox this for 3.0

**Comment by lmolkova** [comment]
yes, we need docs for all W3C changes cross .NET, ASP.NET Core and ASP.NET. I have it on my list, but likely won't come across it before Oct.
