### ISSUE TITLE
Dll File Version not incremented between versions

### ISSUE THREAD

**Issue by ComradeCow** [aspnet/Microsoft.AspNet.TelemetryCorrelation#29]
We're developing an ASP MVC 4 website that must be deployed via an InstallShield installer.  We've had the `Microsoft.AspNet.TelemetryCorrelation` package installed a v1.0.0 for a while, but when we updated the package to v1.0.3, InstallShield stopped updating the dll.

After inspecting the changes, we noticed the File Version does not increase for each version of the package.

Package Version | Product Version | File Version
------------------|--------------------|----------------
1.0.0  | 1.0.0-10628 | 1.0.10628.0
1.0.1 | 1.0.1-10330 | 1.0.10330.0
1.0.3 | 1.0.3-10426 | 1.0.10426.0

The _v1.0.0 file version_ (10628) _is greater than the v1.0.3 file version_ (10426). During updates, InstallShield will not drop the upgraded version of the DLL because 1.0.10426.0 is not greater than 1.0.10628.0. The web site would only show an error saying it couldn't load Microsoft.AspNet.TelemetryCorrelation.dll.   For the time being we rolled back the update.

We would like to be able to install the newest version (v1.0.3) and deploy it with our installer without having to add extra configuration in the installer to ignore version issues, etc.

**Comment by SergeyKanzhelev** [comment]
Should be fixed now as file version is taken from time-based calculation:

```
<VersionStartYear>2018</VersionStartYear>

<VersionBuild 
    Condition="'$(VersionBuild)' == '' OR '$(VersionBuild)' == '0'">
    $([MSBuild]::Add(
        1, 
        $([MSBuild]::Subtract($([System.DateTime]::Now.Year), $(VersionStartYear)))))
        $([System.DateTime]::Now.ToString("MMdd"))
</VersionBuild>

<FileVersion>$(VersionMajor).$(VersionMinor).$(VersionBuild).$(VersionRevision)</FileVersion>
```


which produces version [assembly: AssemblyFileVersion("1.0.10831.0")] (1 year since 2018m Aug (08) 31st).
