### ISSUE TITLE
System.Diagnostics.DiagnosticSource.dll out of date, not compatible with other AI dependencies

### ISSUE THREAD

**Issue by the-jerri** [aspnet/Microsoft.AspNet.TelemetryCorrelation#32]
Just tried updating all my dependent assemblies in a huge project, and AI is causing me some headaches. Currently, it seems it's the _TelemetryCorrelation_ library that is the culprit.

_System.Diagnostics.DiagnosticSource, **Version=4.0.2.0**_ is referenced by this library, however, all other AI dependencies are currently targetting _System.Diagnostics.DiagnosticSource, **Version=4.0.3.0**_.

This causes issues, throwing FileNotFoundException all over the place. Tried working around the issue by setting dependent assembly in web.config but the problem remains.

Attaching images from JustDecompile and AsmSpy for reference.

![image](https://user-images.githubusercontent.com/38536164/44334185-22636880-a471-11e8-8754-101d842e550e.png)

![image](https://user-images.githubusercontent.com/38536164/44334225-3d35dd00-a471-11e8-81df-0dae62655ee2.png)

**Comment by lmolkova** [comment]
I'm sorry it caused you so much headache. 

We'll update reference to DiagnosticSource here, but it's expected that different libraries depend on different versions of the same dependency. Binding redirects are intended to solve this issue. If you update nuget package via VS or nuget install, binding redirects are updated automatically and redirect calls to the latest version (or one you specify). Do you have proper binding redirects in web.config?

**Comment by lmolkova** [comment]
Feel free to reopen as needed.

**Comment by daniel-sousa-lobo** [comment]
I have the same problem, and I have the proper redirects in web.config, which do not work.
