### ISSUE TITLE
If TelemetryCorrelationHttpModule is not the first in pipeline, correlation may be broken

### ISSUE THREAD

**Issue by lmolkova** [aspnet/Microsoft.AspNet.TelemetryCorrelation#42]
See https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/1049

In web.config transformation, insert TelemetryCorrelationHttpModule to be the first in pipeline

Do not make TelemetryCorrelationHttpModule create another Activity if one was already created.

**Comment by SergeyKanzhelev** [comment]
Can you give TLDR - is it dup of https://github.com/aspnet/Microsoft.AspNet.TelemetryCorrelation/issues/17 or separate issue?

**Comment by lmolkova** [comment]
this is dup.
